theme: jekyll-theme-minimal
title: Charlie Mei
description: strategy & analytics / cu / nyc / au
logo: assets/favicon.png

social_links:
  linkedin:  https://www.linkedin.com/in/charlie-mei/
  github: https://github.com/Charlie-Mei