title: Charlie Mei
email: charlie.mei@outlook.com
description:
  strategy analytics / cu '21 / unimelb '16 / nyc / au
baseurl: ""
url: ""
github_username:  Charlie-Mei
linkedin_username: Charlie Mei

# Show excerpts
show_excerpts: true

# Build settings
theme: minima